### ISSUE TITLE
Présence de mots offensants

### ISSUE THREAD

**Issue by rdubigny** [ArthurPons/diceware-fr-alt#2]
Les mots suivants sont peu sûr dans un cadre professionnel voir offensants :

- gonzesse
- gouine
- urine
- urinoir

**Comment by rdubigny** [comment]
suggestion de remplacement :

- caneton
- citrouille
- grenouille
- ecureuil

**Comment by renardpal** [comment]
c'est aussi le cas de :
- turf
- tuerie
- tueur
- tueuse
- travelo
- toxico
- tata
- tombeur
- tombeuse
- taulard
- taularde
- urine
- urinoir
- vagin
- verge
- vicelard
- vicelarde
- vichy
- vicieux
- vicieuse
- vinasse
- violeur
- vioque
- wharf
- zonard
- zonarde

**Comment by renardpal** [comment]
et d'autres mots dont on pourrait se passer : 
- allumeur
- allumeuse
- anus
- aryen
- aryenne
- bastos
- bigleux
- bigleuse
- bignole
- bisexuel
- chatte
- couillon
- cradingue
- crade
- derche
- drague
- dragueur
- dragueuse
- ecstasy
- emmerdant
- emmerde
- esclavage
- esclave
- excitante
- facho
- flicaille
- flicard
- flirt
- garce
- glaviot
- gonze
- gonzesse
- gouine
- gravosse
- gretchen
- gringo
- jouasse
- jouissif
- jouissive
- lesbien
- lesbienne
- libertin
- libertine
- libido
- lolo
- lope
- loquedu
- mamelle
- mamelon
- mameluk
- marijuana
- maton
- matonne
- mauviette
- meuf
- meurtre
- meurtrier
- micheton
- midinette
- minet
- minette
- moujingue
- nibard
- nichon
- orgasme
- orgie
- ovaire
- overdose
- ovule
- potiche
- racaille
- sadique
- sadisme
- salingue
- saloperie
- skinhead
- skunks
- soubrette
- sperme
- suicidaire
- suicide
-

**Comment by rdubigny** [comment]
suggestion de remplacement : 

abrupt
absolu
aigle
aile
alto
balade
barde
basique
bleu
boite
cailloux
cedex
char
civil
digne
dorsal
drastique
duplicata
endormi
environ
escrimeur
estival
exact
export
fade
familial
fleuri
foule
genoux
giron
glace
glossaire
golf
graphique
graphiste
groupe
jaguar
jaune
jovial
kiosque
lacunaire
lest
levain
levure
lexical
lexique
lieu
local
longitude
machinal
malotru
mangeoire
marchand
matinal
melon
menthe
menu
minitel
mode
mousse
mythe
noix
nominatif
nutritif
nutrition
obtention
ombre
onze
original
page
pain
paire
papa
pause
plume
polissage
potiron
poule
prieur
public
raffinage
raide
rare
rectorat
reine
rose
rouge
sage
salin
satire
satirique
superflu
tabou
tannique
total
turbo
vague
vase
vecteur
vrai
voici
vermeil
versatile
ville
yeux
zone

**Comment by ArthurPons** [comment]
Merci !
